sonar.projectKey=jcontiero_oficina-database-infra
sonar.organization=jcontiero

sonar.projectName=oficina-database-infra
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.terraform/**,**/node_modules/**
sonar.sourceEncoding=UTF-8

# Regras S7637 (SHA em workflows de CI/CD), S6258 (log_checkpoints) e S6403 (ssl_mode em rede privada interna)
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=terraform:*
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.tf
